---
name: Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        run: |
          rustup toolchain install nightly --profile minimal -c rustfmt,clippy

      - name: Install Biome
        run: |
          curl -L "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%402.0.0-beta.5/biome-linux-x64" -o /usr/local/bin/biome
          chmod +x /usr/local/bin/biome

      - name: Rust Format
        run: |
          cargo +nightly fmt --all -- --check

      - name: Rust Clippy
        run: |
          cargo +nightly clippy --all-targets -- -D clippy::all

      - name: Biome Format
        run: |
          biome format --error-on-warnings --indent-style=space src/static/index.js

      - name: Biome Lint
        run: |
          biome lint --error-on-warnings src/static/index.js
